version: "3"
services:
  php:
    image: yiisoftware/yii2-php:7.1-apache
    container_name: tiago-app
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - nfsmount:/app:delegated
    ports:
      - "8080:80"

  db:
    image: mysql
    container_name: tiago-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: api

  adminer:
    image: adminer
    container_name: tiago-adminer
    restart: always
    ports:
      - 8081:8080

volumes:
  mysql:
  nfsmount:
    driver: local
    driver_opts:
      type: nfs
      o: addr=host.docker.internal,rw,nolock,hard,nointr,nfsvers=3
      device: ":/System/Volumes/Data/${PWD}"
